### PR TITLE
engine config update

### LINKED ISSUE #18: Types file outdated
The index.d.ts file is outdated. It contains incorrect configuration keys (`Engineconfig.stores.memcaches`) and missing keys (`Engineconfig.queryCache`).

### PR DESCRIPTION
**Pull request by thepwagner**
Fixes #18

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -16,59 +16,61 @@ const LineWrapper = require('stream-line-wrapper');
...
-        epoch?: number,
-        timeout?: string,
-        memcaches: [
-            {
-                url: string
-            }
-        ]
-    }[]
-    ,
-    operations?: {
```
Comment (glasser) [inline src/index.ts]: Isn't this still in the proxy?

Comment (thepwagner) [reply src/index.ts]: Yes; but it's not documented anywhere, and is deprecated in favour of https://github.com/apollographql/apollo-cache-control.
